### ISSUE TITLE
Verify crossplay compatibility with Steam/GOG.

### ISSUE THREAD

**Issue by DaloLorn** [OpenSRProject/OpenStarRuler#1]
In the long term, we'll probably have to make a regular procedure of this sort of thing, testing compatibility between every new revision and its last Steam-compatible predecessor. Ideally, I think we should strive to preserve compatibility as long as possible, but if the time comes... we absolutely mustn't be blindsided by a sudden loss of compatibility.

First, though, we need to identify the latest revision that's still capable of playing multiplayer with the commercial clients. Considering the lessons learned from previous incidents, it should be assumed that crossplay compatibility is (somehow) not commutative, and we should test and record for both of the possible client/server combinations.

**Comment by Skeletonxf** [comment]
For starters, we know that the extra two shipsets cause immediate CTD if they are present on only the client or host. I think those should be removed from the data distribution and left only in the mod pack.

**Comment by DaloLorn** [comment]
They will be. The data repo will be rolled back to the original Blind Mind source dump, as soon as I've pulled all its changes into the modpack.

I might do it today, if nothing else gets in the way.

**Comment by Skeletonxf** [comment]
So you want to opt for testing each addition not breaking things rather than trying to pull out each thing that breaks stuff?

**Comment by DaloLorn** [comment]
This still needs to be tested at some point. The data incompatibilities have been resolved, but we still don't know which C++ changes (if any) are breaking binary compatibility with the commercial clients.

**Comment by kb-1000** [comment]
On a first look through the history (https://github.com/BlindMindStudios/StarRuler2-Source/commits/master/source), I do not see any changes affecting this.
Of course, there could be something before open-sourcing.

**Comment by DaloLorn** [comment]
Well, the idea was to run through each revision until we found the latest compatible build. Looking at the history doesn't tell *me* there's something wrong, either, but we should find out if there *is* (which I think there was), and then work our way back until we pin it down.

**Comment by DaloLorn** [comment]
@Skeletonxf My memory's a bit fuzzy - did we end up pinning the crossplay issues on Rising Stars somehow? I'm toying with the notion of tagging a v1.0 release, but I feel a little silly doing that before we've fixed that (if there was anything *to* fix engine-side). 😂

**Comment by Skeletonxf** [comment]
No, but cross play in vanilla, my own mod, and just the modpack seemed to work fine last time we were testing.

**Comment by DaloLorn** [comment]
That basically amounts to pinning it on RS. 😛

Might be worth investigating what and why, but... eh, if it's caused by a mod, it can probably be fixed (or at least haphazardly patched) by a mod.

**Comment by DaloLorn** [comment]
Closing this to prevent confusion.
