### ISSUE TITLE
Ubuntu Workaround

### ISSUE THREAD

**Issue by odysseyalive** [OpenSRProject/OpenStarRuler#13]
I couldn't get OpenSR to start initially. The latest Ubuntu comes with Glew 2.2, but OpenSR doesn't recognize it.

Installing the Glew 2.1 package from Focal is a safe workaround: https://packages.ubuntu.com/focal/amd64/libglew2.1/download

**Comment by kb-1000** [comment]
#12 would fix this, but it unfortunately doesn't work on Windows yet
