### ISSUE TITLE
Figure out build automation.

### ISSUE THREAD

**Issue by DaloLorn** [OpenSRProject/OpenStarRuler#2]
Not all OpenSR contributors should be expected to be capable of building releases for every supported platform. For instance, I can relatively comfortably build Win64 and Win32 binaries, but would take forever to set up just *one* proper Linux build (probably Ubuntu, since that's what all my Linux VMs so far have been using). Others may not have a Windows machine to build on, or might not know how to build for Windows. And odds are just about nobody can be expected to singlehandedly build the game for all the countless Linux distros out there.

However, it's my understanding that there are online services that the build process could be offloaded to. We should probably figure out how to use one of those services.

**Comment by kb-1000** [comment]
I'm using Fedora for my own purposes however, and COPR would require that as well. Fedora uses dnf and not apt, and the packages have a slightly different naming scheme. Of course, it shouldn't be too hard to adapt. It WOULD however be useful almost as-is for things like a generic Linux build, a Snap or a PPA.

**Comment by DaloLorn** [comment]
I feel like we've got it all figured out now, soooo... closing.
